### MAJESTIC BLUSH ###
DEFAULT_MB_BG_COLOR = "#FF78C4"
DEFAULT_MB_BUTTONS_BG_COLOR = "#FFBDF7"
DEFAULT_MB_BUTTONS_FG_COLOR = "black"
DEFAULT_MB_LABELS_BG_COLOR = "#FF78C4"
DEFAULT_MB_LABELS_FG_COLOR = "black"

### DARK MODE ###
DEFAULT_DM_BG_COLOR = "#13005A"
DEFAULT_DM_BUTTONS_BG_COLOR = "#2F58CD"
DEFAULT_DM_BUTTONS_FG_COLOR = "white"
DEFAULT_DM_LABELS_BG_COLOR = "#13005A"
DEFAULT_DM_LABELS_FG_COLOR = "light green"

### LIGHT MODE ###
DEFAULT_LM_BG_COLOR = "#E3F6FF"
DEFAULT_LM_BUTTONS_BG_COLOR = "#AED6F1"
DEFAULT_LM_BUTTONS_FG_COLOR = "black"
DEFAULT_LM_LABELS_BG_COLOR = "#E3F6FF"
DEFAULT_LM_LABELS_FG_COLOR = "black"

### CLASSIC DARK MODE ###
DEFAULT_CDM_BG_COLOR = "#2A3990"
DEFAULT_CDM_BUTTONS_BG_COLOR = "#251749"
DEFAULT_CDM_BUTTONS_FG_COLOR = "white"
DEFAULT_CDM_LABELS_FG_COLOR = "white"
DEFAULT_CDM_LABELS_BG_COLOR = "#2A3990"

### CLASSIC LIGHT MODE ###
DEFAULT_CLM_BG_COLOR = "light blue"
DEFAULT_CLM_BUTTONS_FG_COLOR = "black"
DEFAULT_CLM_BUTTONS_BG_COLOR = "white"
DEFAULT_CLM_LABELS_BG_COLOR = "light blue"
DEFAULT_CLM_LABELS_FG_COLOR = "black"



### HOVER COLORS ### 

DEFAULT_DM_HOVER_BUTTON_COLOR = "#86A3B8"
DEFAULT_LM_HOVER_BUTTON_COLOR = "#E5E0FF"
DEFAULT_CDM_HOVER_BUTTON_COLOR = "black"
DEFAULT_CLM_HOVER_BUTTON_COLOR = "#ECECEC"
DEFAULT_MB_HOVER_BUTTON_COLOR = "#FFECEC"

